module.exports = {
  // Airbnb styles
  arrowParens: 'avoid',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  printWidth: 100,
  proseWrap: 'always',
  quoteProps: 'as-needed',
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
  // Remaining Defaults
  bracketSameLine: false,
  // embeddedLanguageFormatting: 'auto',
  // endOfLine: 'lf',
  // filepath: undefined,
  // htmlWhitespaceSensitivity: 'css',
  // insertPragma: false,
  // parser: undefined,
  // rangeEnd: Infinity,
  // requirePragma: false,
  // singleAttributePerLine: false,
  // vueIndentScriptAndStyle: false,
};

// All defaults
// {
//   arrowParens: 'always',
//   bracketSameLine: false,
//   bracketSpacing: true,
//   embeddedLanguageFormatting: 'auto',
//   endOfLine: 'lf',
//   filepath: undefined,
//   htmlWhitespaceSensitivity: 'css',
//   insertPragma: false,
//   jsxBracketSameLine: false,
//   jsxSingleQuote: false,
//   parser: undefined,
//   printWidth: 80,
//   proseWrap: 'preserve',
//   quoteProps: 'as-needed',
//   rangeEnd: Infinity,
//   requirePragma: false,
//   semi: true,
//   singleAttributePerLine: false,
//   singleQuote: false,
//   tabWidth: 2,
//   trailingComma: 'es5',
//   useTabs: false,
//   vueIndentScriptAndStyle: false,
// }
